// MON-04 metrics package unit tests.
//
// These tests intentionally avoid any Postgres dependency — the DB refresh
// goroutine is exercised separately via integration (the unit slice here
// only checks the SQL string + nil-handling). To keep CI fast we operate
// against a fresh registry per test so collector state is hermetic.
package metrics

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/prometheus/client_golang/prometheus/testutil"
)

// TestNew_RegistersExpectedCollectors verifies every documented metric
// name is present after New() (with at least one observation so the
// text exposition format actually emits a line for label-vec collectors).
// If you add or rename a collector, this test will fail until you also
// update Grafana dashboards / alert rules.
func TestNew_RegistersExpectedCollectors(t *testing.T) {
	m := New()

	// Force one observation on every *Vec collector — Prometheus omits
	// vec collectors that have never been touched from the text output.
	// Plain gauges/counters appear regardless.
	m.VPNThroughputBytes.WithLabelValues("rx").Add(0)
	m.SignupsTotal.WithLabelValues("device").Add(0)
	m.PaymentsTotal.WithLabelValues("apple_iap", "completed").Add(0)
	m.AppEventsTotal.WithLabelValues("app.launch").Add(0)
	m.HTTPDuration.WithLabelValues(http.MethodGet, "/test", "2xx").Observe(0)
	m.DBQueryDuration.WithLabelValues("SELECT").Observe(0)
	m.RedisCacheHits.WithLabelValues("idempotency").Add(0)
	m.RedisCacheMisses.WithLabelValues("idempotency").Add(0)

	want := []string{
		// Live VPN load
		"chameleon_vpn_users_online",
		"chameleon_vpn_throughput_bytes_total",
		"chameleon_vpn_tcp_retransmit_total",
		"chameleon_vpn_tcp_segments_sent_total",
		"chameleon_vpn_active_connections",
		// Funnel
		"chameleon_signups_total",
		"chameleon_payments_total",
		"chameleon_app_events_total",
		"chameleon_dau_users",
		// Backend internals
		"chameleon_http_request_duration_seconds",
		"chameleon_db_query_duration_seconds",
		"chameleon_redis_cache_hit_total",
		"chameleon_redis_cache_miss_total",
		// Default Go runtime — proves NewGoCollector was registered.
		"go_goroutines",
		"go_memstats_alloc_bytes",
		"process_cpu_seconds_total",
	}

	rec := httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodGet, "/metrics", nil)
	m.Handler().ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Fatalf("/metrics status = %d, want 200", rec.Code)
	}
	body := rec.Body.String()
	for _, name := range want {
		if !strings.Contains(body, name) {
			t.Errorf("expected metric %q in /metrics output, not found", name)
		}
	}
}

// TestObserveHTTP_OneObservationPerCall — exactly one bucket increment
// per ObserveHTTP() call. Catches accidental double-recording when the
// middleware wraps next() twice or fires from both panic-recover + happy-path.
func TestObserveHTTP_OneObservationPerCall(t *testing.T) {
	m := New()
	m.ObserveHTTP(http.MethodGet, "/api/v1/test", http.StatusOK, 50*time.Millisecond)

	// Count is metric-cardinality-aware: WithLabelValues returns a
	// Histogram; the sum-of-buckets equals the total observations.
	got := testutil.CollectAndCount(m.HTTPDuration, "chameleon_http_request_duration_seconds")
	// CollectAndCount returns the number of label tuples emitted; the
	// total observation count for that tuple is what we want.
	if got != 1 {
		t.Fatalf("label tuples emitted = %d, want 1", got)
	}

	// Now drive a second call with a DIFFERENT route — should be 2 tuples.
	m.ObserveHTTP(http.MethodPost, "/api/v1/other", http.StatusCreated, 5*time.Millisecond)
	got = testutil.CollectAndCount(m.HTTPDuration, "chameleon_http_request_duration_seconds")
	if got != 2 {
		t.Fatalf("label tuples after 2nd unique observe = %d, want 2", got)
	}
}

// TestObserveHTTP_BoundedCardinality — feeding 500 distinct status codes
// (real URLs would never do this — that's the point) MUST still bound at
// 4 status_class buckets, not 500. This is the safety net for the
// cardinality rule documented in the package doc.
func TestObserveHTTP_BoundedCardinality(t *testing.T) {
	m := New()
	for i := 0; i < 500; i++ {
		m.ObserveHTTP(http.MethodGet, "/api/v1/users/:id", 200+i%300, time.Millisecond)
	}
	tuples := testutil.CollectAndCount(m.HTTPDuration, "chameleon_http_request_duration_seconds")
	// Possible status_class values: 2xx, 3xx, 4xx, 5xx — at most 4 tuples
	// for one (method, route) pair. (1xx not generated by this loop.)
	if tuples > 4 {
		t.Fatalf("cardinality unbounded: %d tuples, want ≤ 4", tuples)
	}
}

// TestObserveHTTP_EmptyRouteCollapsesToUnmatched ensures requests that
// didn't match any registered Echo route (c.Path() returns "") go into a
// single 'unmatched' bucket instead of an empty-string label that would
// look broken in Grafana.
func TestObserveHTTP_EmptyRouteCollapsesToUnmatched(t *testing.T) {
	m := New()
	m.ObserveHTTP(http.MethodGet, "", http.StatusNotFound, time.Millisecond)
	rec := httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodGet, "/metrics", nil)
	m.Handler().ServeHTTP(rec, req)
	body := rec.Body.String()
	if !strings.Contains(body, `route="unmatched"`) {
		t.Errorf("expected route=\"unmatched\" label, body did not contain it")
	}
}

// TestProvider_Bounded — anything outside the whitelist drops into
// "other", protecting the chameleon_signups_total{provider} cardinality.
func TestProvider_Bounded(t *testing.T) {
	cases := []struct {
		in, want string
	}{
		{"apple", "apple"},
		{"APPLE", "apple"},
		{" google ", "google"},
		{"device", "device"},
		{"telegram", "telegram"},
		{"email", "email"},
		{"", "other"},
		{"facebook", "other"},
		{"random-garbage", "other"},
	}
	for _, tc := range cases {
		if got := Provider(tc.in); got != tc.want {
			t.Errorf("Provider(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func TestPaymentSource_Bounded(t *testing.T) {
	for _, in := range []string{"apple_iap", "freekassa", "admin"} {
		if got := PaymentSource(in); got != in {
			t.Errorf("PaymentSource(%q) = %q, want %q", in, got, in)
		}
	}
	if got := PaymentSource("paypal"); got != "other" {
		t.Errorf("PaymentSource(paypal) = %q, want other", got)
	}
}

func TestPaymentStatus_Bounded(t *testing.T) {
	for _, in := range []string{"completed", "pending", "failed", "refunded"} {
		if got := PaymentStatus(in); got != in {
			t.Errorf("PaymentStatus(%q) = %q, want %q", in, got, in)
		}
	}
	if got := PaymentStatus("???"); got != "other" {
		t.Errorf("PaymentStatus(???) = %q, want other", got)
	}
}

func TestAppEventName_Whitelist(t *testing.T) {
	cases := []struct {
		in, want string
	}{
		{"app.launch", "app.launch"},
		{"paywall.view", "paywall.view"},
		{"paywall.purchase_success", "paywall.purchase_success"},
		{"vpn.connect.start", "vpn.connect.start"},
		{"vpn.connect.success", "vpn.connect.success"},
		{"vpn.connect.fail", "vpn.connect.fail"},
		{"app.background", "app.background"},
		{"app.foreground", "app.foreground"},
		// Unknown event names are bounded to "other".
		{"unknown.event", "other"},
		{"", "other"},
	}
	for _, tc := range cases {
		if got := AppEventName(tc.in); got != tc.want {
			t.Errorf("AppEventName(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

// TestDBOperation_FirstVerb — only SELECT/INSERT/UPDATE/DELETE pass through;
// anything else is "other" so DDL or vendor-specific verbs don't show up
// as fresh labels.
func TestDBOperation_FirstVerb(t *testing.T) {
	cases := []struct {
		in, want string
	}{
		{"SELECT * FROM users", "SELECT"},
		{"select id from users", "SELECT"},
		{"  INSERT INTO foo VALUES (1)", "INSERT"},
		{"UPDATE users SET x=1", "UPDATE"},
		{"DELETE FROM logs", "DELETE"},
		{"TRUNCATE TABLE x", "other"},
		{"WITH cte AS (...)", "other"},
		{"", "other"},
	}
	for _, tc := range cases {
		if got := DBOperation(tc.in); got != tc.want {
			t.Errorf("DBOperation(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func TestStatusClass(t *testing.T) {
	cases := []struct {
		code int
		want string
	}{
		{100, "1xx"}, {200, "2xx"}, {299, "2xx"},
		{301, "3xx"}, {404, "4xx"}, {500, "5xx"},
		{599, "5xx"}, {0, "unknown"},
	}
	for _, tc := range cases {
		if got := StatusClass(tc.code); got != tc.want {
			t.Errorf("StatusClass(%d) = %q, want %q", tc.code, got, tc.want)
		}
	}
}

// TestCacheHitMiss_NilSafe — handlers may receive a nil *Metrics (no
// metrics wired in tests). The convenience wrappers MUST tolerate that.
func TestCacheHitMiss_NilSafe(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Fatalf("nil-receiver panicked: %v", r)
		}
	}()
	var m *Metrics
	m.CacheHit("anything")
	m.CacheMiss("anything")
}

// TestCountSignup_PostsToProvider ensures the counter materialises in the
// /metrics output for the right provider label.
func TestCountSignup_PostsToProvider(t *testing.T) {
	m := New()
	m.CountSignup("apple")
	m.CountSignup("apple")
	m.CountSignup("google")
	m.CountSignup("totally-not-a-provider") // becomes "other"

	rec := httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodGet, "/metrics", nil)
	m.Handler().ServeHTTP(rec, req)
	body := rec.Body.String()
	for _, want := range []string{
		`chameleon_signups_total{provider="apple"} 2`,
		`chameleon_signups_total{provider="google"} 1`,
		`chameleon_signups_total{provider="other"} 1`,
	} {
		if !strings.Contains(body, want) {
			t.Errorf("/metrics body missing %q\nBODY:\n%s", want, body)
		}
	}
}

// TestCountPayment_DimensionsMatrix — counter increments must propagate
// the full (source, status) cardinality without dropping any axis.
func TestCountPayment_DimensionsMatrix(t *testing.T) {
	m := New()
	m.CountPayment("apple_iap", "completed")
	m.CountPayment("freekassa", "failed")
	m.CountPayment("admin", "refunded")
	m.CountPayment("crypto-unknown", "pending") // source → other

	rec := httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodGet, "/metrics", nil)
	m.Handler().ServeHTTP(rec, req)
	body := rec.Body.String()
	for _, want := range []string{
		`chameleon_payments_total{source="apple_iap",status="completed"} 1`,
		`chameleon_payments_total{source="freekassa",status="failed"} 1`,
		`chameleon_payments_total{source="admin",status="refunded"} 1`,
		`chameleon_payments_total{source="other",status="pending"} 1`,
	} {
		if !strings.Contains(body, want) {
			t.Errorf("/metrics body missing %q\nBODY:\n%s", want, body)
		}
	}
}
